pipeline {
    agent any

    environment {
        BRANCH_NAME = "tanvi" // Your branch name
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "tanvi", url: 'https://github.com/TanV-04/DevOps_Lab_5.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                script {
                    // Ensure Python is installed on the Jenkins agent
                    bat 'python --version'
                    bat 'python -m venv venv'
                    bat 'venv\\Scripts\\activate'
                    bat 'pip install -r Project1\\requirements.txt'
                }
            }
        }

        stage('Run Python App') {
            steps {
                script {
                    // Run the app.py inside the Project1 folder
                    bat 'venv\\Scripts\\activate && python Project1\\app.py'
                }
            }
        }
    }

    post {
        success {
            echo "App executed successfully"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}
