pipeline {
    agent { label 'linux' }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'tanvi', url: 'https://github.com/TanV-04/DevOps_Lab_5.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t my-flask-app Project1'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Run container detached (adjust as needed)
                    sh 'docker run -d -p 5000:5000 --name flask-app my-flask-app'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'docker stop flask-app || true'
            sh 'docker rm flask-app || true'
        }
    }
}
