version: '3.8'
services:
  angular-app:
    build: .
    ports:
      - "4200:80"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["nginx", "-g", "daemon off;"]
   
