pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                checkout scm
            }
        }
        
        stage('List Files') {
            steps {
                echo 'Listing files in workspace...'
                sh 'find . -name "*.java" -type f'
                sh 'find . -name "Dockerfile" -type f'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building Java application...'
                sh 'cd docker-assignments/project1-jenkins && ls -la'
                sh 'cd docker-assignments/project1-jenkins && javac App.java'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'cd docker-assignments/project1-jenkins && java App'
            }
        }
        
        stage('Docker Build') {
            steps {
                echo 'Building Docker image...'
                sh 'cd docker-assignments/project1-jenkins && docker build -t my-java-app:${BUILD_NUMBER} .'
            }
        }
        
        stage('Docker Run Test') {
            steps {
                echo 'Testing Docker container...'
                sh 'docker run --rm my-java-app:${BUILD_NUMBER}'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deployment completed successfully!'
                echo "Docker image my-java-app:${BUILD_NUMBER} built successfully"
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}