version: "3.9"


services:
dind:
image: docker:26-dind
privileged: true
environment:
- DOCKER_TLS_CERTDIR=
ports:
- "2375:2375" # Expose docker daemon (insecure, for local demo)
command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
volumes:
- dind-storage:/var/lib/docker


jenkins:
build:
context: ./jenkins
dockerfile: Dockerfile
container_name: jenkins
user: root
ports:
- "8080:8080"
- "50000:50000"
environment:
- DOCKER_HOST=tcp://dind:2375
- JENKINS_ADMIN_ID=admin
- JENKINS_ADMIN_PASSWORD=admin123
volumes:
- jenkins_home:/var/jenkins_home
depends_on:
- dind


app:
build:
context: ./app
image: demo/flask-app:local
ports:
- "8000:8000"
environment:
- FLASK_ENV=production
deploy:
replicas: 1
restart: unless-stopped


volumes:
jenkins_home:
dind-storage: