apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: load
    image: busybox:1.28
    command:
      - /bin/sh
      - -c
      - |
        while true; do
          wget -q -O- http://php-apache;
          sleep 0.01;
        done
  restartPolicy: Always
