version: "3.8"

services:
  # Production Angular application
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: angular-prod-app
    restart: unless-stopped
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
