services:
  # Development Angular application
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    container_name: angular-dev-app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - angular-dev-network
    command: npm start

networks:
  angular-dev-network:
    driver: bridge
