pipeline {
  agent none

  stages {
    stage('Checkout') {
      agent { label 'compile' }
      steps {
        git branch: 'soumili', url: 'https://github.com/TanV-04/DevOps_Lab_5.git'
      }
    }
    stage('Compile') {
      agent { label 'compile' }
      steps {
        dir('Devopslab_PROJECT4') {
          bat 'mvn clean compile'
        }
      }
    }
    stage('Test') {
      agent { label 'test' }
      steps {
        dir('Devopslab_PROJECT4') {
          bat 'mvn test'
        }
      }
    }

    stage('Package') {
        agent { label 'compile' }
        steps {
            dir('Devopslab_PROJECT4') {
                bat 'mvn clean package'
            }
        }
    }

    stage('Archive') {
        steps {
            archiveArtifacts artifacts: 'Devopslab_PROJECT4/target/*.jar', fingerprint: true
        }
    }


  }
}
