pipeline {
  agent none

  stages {
    stage('Checkout') {
      agent { label 'compile' }
      steps {
        git branch: 'soumili', url: 'https://github.com/TanV-04/DevOps_Lab_5.git'
      }
    }
    stage('Compile') {
      agent { label 'compile' }
      steps {
        bat 'mvn clean compile'
      }
    }
    stage('Test') {
      agent { label 'test' }
      steps {
        bat 'mvn test'
      }
    }
  }
}
