# Use Node.js 20 (Alpine is lightweight)
FROM node:20-alpine

# Set working directory inside container
WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Angular dev server port
EXPOSE 4200

# Start Angular app in development mode
CMD ["ng", "serve", "--host", "0.0.0.0"]
