pipeline {
    agent none
    stages {
        stage('Compile on Slave 1') {
            agent { label 'slave1' }
            steps {
                echo 'Compiling on Slave 1...'
                sh 'mvn clean compile'
            }
        }
        stage('Test on Slave 2') {
            agent { label 'slave2' }
            steps {
                echo 'Testing on Slave 2...'
                sh 'mvn test'
            }
        }
    }
    post {
        always {
            junit '**/target/surefire-reports/*.xml'
            cleanWs()
        }
    }
}
