pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-app"
        IMAGE_TAG = "latest"
    }


    stages {
        stage('Clean Workspace') {
            steps {
                // This command wipes the workspace before starting
                cleanWs()
            }
        }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'Sushrut', url: 'https://github.com/TanV-04/DevOps_Lab_5.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    echo "Building Docker image..."
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    echo "Running tests in Docker container..."
                    docker run --rm ${IMAGE_NAME}:${IMAGE_TAG} echo "Tests executed successfully"
                '''
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                    echo "Deploying container..."
                    docker run -d --name my-app-container -p 8080:8080 ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
}
