apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-deployment
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: socialmedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialmedia
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: socialmedia
    spec:
      containers:
      - name: socialmedia-app
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30